[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
sepolian = "${SEPOLIA}"
mumbai = "${MUMBAI}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${POLY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config